const ROLES = {
  ORG_ADMIN: "ORG_ADMIN",
  PRODUCT_MANAGER: "PRODUCT_MANAGER",
  TEAM_LEAD: "TEAM_LEAD",
  MEMBER: "MEMBER",
  VIEWER: "VIEWER",
};

const TASK_STATUS = {
  BACKLOG: "BACKLOG",
  TODO: "TODO",
  IN_PROGRESS: "IN_PROGRESS",
  REVIEW: "REVIEW",
  DONE: "DONE",
};

const PRIORITY = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
};

const ACTIVITY_ACTIONS = {
  ORG_CREATED: "ORG_CREATED",
  MEMBER_ADDED: "MEMBER_ADDED",
  MEMBER_REMOVED: "MEMBER_REMOVED",

  TEAM_CREATED: "TEAM_CREATED",
  TEAM_LEAD_ASSIGNED: "TEAM_LEAD_ASSIGNED",

  PROJECT_CREATED: "PROJECT_CREATED",

  TASK_CREATED: "TASK_CREATED",
  TASK_ASSIGNED: "TASK_ASSIGNED",
  TASK_COMPLETED: "TASK_COMPLETED",

  COMMENT_ADDED: "COMMENT_ADDED",

  ROLE_UPDATED: "ROLE_UPDATED",
};

module.exports = {
  ROLES,
  TASK_STATUS,
  PRIORITY,
  ACTIVITY_ACTIONS,
};
