const ROLES = {
  ORG_ADMIN: "ORG_ADMIN",
  PRODUCT_MANAGER: "PRODUCT_MANAGER",
  TEAM_LEAD: "TEAM_LEAD",
  MEMBER: "MEMBER",
  VIEWER: "VIEWER",
};

const TASK_STATUS = {
  BACKLOG: "BACKLOG",
  TODO: "TODO",
  IN_PROGRESS: "IN_PROGRESS",
  REVIEW: "REVIEW",
  DONE: "DONE",
};

const PRIORITY = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
};

module.exports = {
  ROLES,
  TASK_STATUS,
  PRIORITY
}
